#! /bin/bash
# Get various "dotfiles" and move them around

# Make directories
mkdir -pv ./.config/i3
mkdir -pv ./.config/dunst
mkdir -pv ./.config/redshift
mkdir -pv ./.config/fish
mkdir -pv ./.config/fish/functions
mkdir -pv ./.config/fish/conf.d
mkdir -pv ./.config/omf
mkdir -pv ./.config/conky
mkdir -pv ./.config/polybar
mkdir -pv ./.vim/colors/material-dark/vim
mkdir -pv ./bin


# Hard link a file from ~ to .
link () {
    ln -v ~/"$1" ./"$1" || true
}


# Hard link files

# Fish
ln -v ~/.config/i3/* ./.config/i3 || true
ln -v ~/.config/fish/functions/* ./.config/fish/functions/ || true
ln -v ~/.config/fish/conf.d/* ./.config/fish/conf.d/ || true
ln -v ~/.config/omf/* ./.config/omf/ || true
link .config/fish/config.fish
link .config/fish/fish_variables

# Other config
link .config/picom.conf
link .config/dunst/dunstrc
link .config/redshift/redshift.conf

# Misc
link .Xresources
link .gitconfig
link .bashrc
link .ombrc
link .xinitrc
link .Xmodmap
link .zshrc
link .vimrc

# Vim
link .vim/colors/build
link .vim/colors/material-dark.js
link .vim/colors/material-dark.vim
link .vim/colors/material-dark/README.md
link .vim/colors/material-dark/vim/ThemerVim.vim

# Conky
link .config/conky/conky_maia
link .config/conky/conky1.10_shortcuts

# Polybar
link .config/polybar/config.ini

# Bin
ln ~/bin/* ./bin || true

# Libinput
link .config/libinput-gestures.conf


# List packages
pacman -Qnqe > ./aur-packages

NPMPackages="$(npm list -g --depth=0 --parseable=true | sed "s/\/usr\/lib\/node_modules\///g")" # List NPM Pacakges
tail -n +2 <<< "$NPMPackages" > ./npm-packages # Get rid of first line (/usr/lib)
