#! /bin/bash
# Fetch files and ln

mkdir -pv ./.config/i3
mkdir -pv ./.config/dunst
mkdir -pv ./.config/redshift
mkdir -pv ./.config/fish
mkdir -pv ./.config/fish/functions
mkdir -pv ./.config/fish/conf.d
mkdir -pv ./.config/omf
mkdir -pv ./.vim/colors/material-dark/vim
mkdir -pv ./conky

link () {
    ln -v ~/"$1" ./"$1" || true
}

link .Xresources
ln -v ~/.config/i3/* ./.config/i3 || true

link .config/fish/config.fish
link .config/fish/fish_variables
ln -v ~/.config/fish/functions/* ./.config/fish/functions/ || true
ln -v ~/.config/fish/conf.d/* ./.config/fish/conf.d/ || true

ln -v ~/.config/omf/* ./.config/omf/ || true
ln -v /usr/share/conky/* ./conky/ || true
link .gitconfig
link .bashrc
link .ombrc
link .xinitrc
link .Xmodmap
link .zshrc
link .config/picom.conf
link .config/dunst/dunstrc
link .config/redshift/redshift.conf
link .vimrc

link .vim/colors/build
link .vim/colors/material-dark.js
link .vim/colors/material-dark.vim
link .vim/colors/material-dark/README.md
link .vim/colors/material-dark/vim/ThemerVim.vim

pacman -Qnqe > ./aur-packages
